### PR TITLE
added `/kick` cmd

### LINKED ISSUE #12: /kick command
Kicks a selected player from a scrim (only useable by mods)

### PR DESCRIPTION
**Pull request by PaulMndn**
Added and tested `/kick` command.
Implemented so that players can only be kicked before the scrim started, but reserves can also be kicked after it started.
Timeout command for #24 coming soon.

closes #12

### CODE REVIEW

**Comment by jaimevisser** [comment]
Neat and small, only problem is that this doesn't kick off an update of the scrim manager (and won't refresh the embed).

**Comment by PaulMndn** [comment]
The `/kick player` command basically calls `ScrimManager().leave(player)`, which intern schedules `self.__update()` to updates itself including the header and content message.

Embed and header message got updated during my testing.

I didn't test the broadcast message but it should update as well as its update method is called within `ScrimManager().__update()`.

**Comment by jaimevisser** [comment]
Chalk it up to Monday morning. Probably going to rename some stuff as
scrimmanager is also called scrim in several places which can be confusing.

**Comment by PaulMndn** [comment]
No worries. 🙂 

Yeah, I've had the same problem in several places too. Was a bit confusing when I first got into the code.

**Pull request merged**
